### ISSUE TITLE
Ability to read from directories instead of .zip files when possible.

### ISSUE THREAD

**Issue by AsherJingkongChen** [ArthurBrussee/brush#1]
**Problem**

We are working with a ZIP file containing several entries, including images and a sparse folder with camera data. Here’s a sample of the ZIP’s contents:

```plaintext
   411837  04-13-2023 16:37   train/images/00300.jpg
   429686  04-13-2023 16:37   train/images/00301.jpg
        0  07-04-2023 16:55   train/sparse/
        0  07-04-2023 16:57   train/sparse/0/
       64  04-13-2023 16:33   train/sparse/0/cameras.bin
```

However, the COLMAP reader is unable to locate files like `sparse/0/cameras.bin` and potentially other entries.

**Question**

What’s the best way to resolve this? Should we try to match against the regular expression `.*sparse/0/cameras.bin` for all entries in the ZIP?

**Concern**

I'm unsure if reading from arbitrary ZIP files using this approach is reliable long-term. Are there any more stable methods for handling this?

**Comment by ArthurBrussee** [comment]
Yeah the format is very finnicky currently - the folder needs to contain _exactly_ an ./images and ./sparse folder. Adding some method to search for the sparse folder should help! The nerf_synthetic reader does already do this.

I agree though it's generally terrible to use a .zip for this, you should be able to just read a directory. I've done it like this so far because it's harder on WASM and Android to open directories.

**Comment by ArthurBrussee** [comment]
I've added some fixes so this should be more robust, and eg. a top level directory in a zip file should be ok now.

Will leave this issue open & change it to say opening normal directories should work

**Comment by lucas-vitrus** [comment]
Do I need both the `train` and `val` folders *and* the Colmap `images` and `sparse`? 
Or is one or the other structure?

<img width="208" alt="image" src="https://github.com/user-attachments/assets/55952996-d9ac-44d8-b5c1-15d7dbc9d8ff">

**Comment by AsherJingkongChen** [comment]
This defines camera poses in Nerf synthetic dataset convention, so you don't need to add sparse and images as COLMAP does.

**Comment by gaojing418** [comment]
![微信截图_20241113212902](https://github.com/user-attachments/assets/0446965c-bae9-49e5-a786-b491c868f9e5)
I used metashape to export the camera and got two folders, but after importing it, it showed that it was not supported.
![Uploading 微信截图_20241113213119.png…]()

**Comment by ArthurBrussee** [comment]
This is now implemented https://github.com/ArthurBrussee/brush/commit/152aad0d59d5aa9d740676459dfbfec74c5abb4b
