### ISSUE TITLE
Feature: Allow opening from URL

### ISSUE THREAD

**Issue by ArthurBrussee** [ArthurBrussee/brush#19]
It would be nice if the web version could be passes a URL to load data from. It could either be a .ply to work as a viewer, or a .zip and start training.

It would be especially nice if this worked with something like Google Drive URLs, but I'm not sure if you can simple download data from those or whether that needs some special authentication.

Would need a simple HTTP library:
- That is async
- ideally compiles down to just a JS fetch() call on wasm

**Comment by AsherJingkongChen** [comment]
How to ensure the safety of ZIP URLs?

**Comment by AsherJingkongChen** [comment]
It depends. I consider the case that a zip file can be decompress in this way:

```plaintext
https://brush-demo.com/?url=https://bad.com/bomb.zip
```

It should be fine if the URL is passed to the obvious `<input>`.

**Comment by ArthurBrussee** [comment]
This is now done post #35 and #37 !

Loading a zip bomb might crash the tab, but that's all it should do, up to Chrome to not have that catastrophically go wrong imo.

**Comment by liftimage3d** [comment]
Get "Error: Failed to download data (are you trying to download from Google Drive? You might have to use the proxy" when inputting a Google Drive URL. Get "Error: error sending request" when inputting a github URL. What format should the URL be when we put ply files on Google Drive or github?
