### ISSUE TITLE
WGPU error: There was no valid format for the surface at all

### ISSUE THREAD

**Issue by zaghetto** [ArthurBrussee/brush#33]
➜  brush git:(main) ✗ RUST_BACKTRACE=full cargo run --release

   Compiling brush-desktop v0.1.0 (/mnt/data01/MachineLearning/PointCloudCompression/3dgs/brush/crates/brush-desktop)
    Finished `release` profile [optimized] target(s) in 5.06s
     Running `target/release/brush_bin`
     
[2024-11-15T02:35:20Z ERROR eframe::native::run] Exiting because of error: WGPU error: There was no valid format for the surface at all.
thread 'main' panicked at crates/brush-desktop/src/main.rs:44:10:
called `Result::unwrap()` on an `Err` value: Wgpu(NoSurfaceFormatsAvailable)
stack backtrace:
   0:     0x560d4abba12a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x560d4abe722b - core::fmt::write::hf5713710ce10ff22
   2:     0x560d4abb5993 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x560d4abbb632 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x560d4abbb29e - std::panicking::default_hook::h81c8cd2e7c59ee33
   5:     0x560d4abbbebf - std::panicking::rust_panic_with_hook::had2118629c312a4a
   6:     0x560d4abbbba7 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   7:     0x560d4abba609 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   8:     0x560d4abbb834 - rust_begin_unwind
   9:     0x560d497a2163 - core::panicking::panic_fmt::h3eea515d05f7a35e
  10:     0x560d497a2636 - core::result::unwrap_failed::h7c8d8bbbcf45dc13
  11:     0x560d497ca458 - brush_bin::main::h3c5a32ecca309821
  12:     0x560d497bb863 - std::sys::backtrace::__rust_begin_short_backtrace::h6a773ef73b90bcd7
  13:     0x560d497c791d - std::rt::lang_start::{{closure}}::h93dd68dd970df060
  14:     0x560d4abad030 - std::rt::lang_start_internal::h4d90db0530245041
  15:     0x560d497ca595 - main
  16:     0x7ffa88c30083 - __libc_start_main
                               at /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
  17:     0x560d497a2a3e - _start
  18:                0x0 - <unknown>

**Comment by ArthurBrussee** [comment]
Hmm this happens when the chosen GPU can’t render UI. Do you have a dedicated and integrated GPu? Is this on Linux? Any way to force dedicated GPU?

Should add some printouts before creating the GUI of the chosen adapter.

**Comment by ArthurBrussee** [comment]
#44 might fix this, if you have a chance to try it let me know!

**Comment by ArthurBrussee** [comment]
Assuming this is fixed after #44
