### ISSUE TITLE
nerf synthetic dataset format not working

### ISSUE THREAD

**Issue by lanxinger** [ArthurBrussee/brush#41]
hi,

we tried loading in the nerf synthetic dataset format as specified 

transform_train.json
and /images folder

but getting an error:
Error: Couldn't parse dataset as a
ny format. Only some formats are supported.

I have attached the dataset here. 
[test.zip](https://github.com/user-attachments/files/17796459/test.zip)

**Comment by ArthurBrussee** [comment]
Hiya, thansk for giving a go!

There were a few issues here:
- The json was named transform_train.json not transforms_train.json
- The data in the json used the [nerfstudio data format](https://docs.nerf.studio/quickstart/data_conventions.html), not the nerf synthetic format.
- It included an initial ply to start from

Supporting those was on my radar anyway so https://github.com/ArthurBrussee/brush/pull/43 fixes this! It also makes the parsing a bit more flexible so it'll just use the ".json" file irregardless of the name (if there's multiple, you'll have to include _train and _val in the name).

![image](https://github.com/user-attachments/assets/7cc56a49-b382-4b18-833d-fcdfa7d9caf9)

**Comment by espressodru** [comment]
Hi, I built the brush and it works with nerfstudio data format now! But maybe a dumb question, I can't find the export button in the preview image and can't export the ply output.

**Comment by ArthurBrussee** [comment]
Hmm strange - do you have a picture of your scene tab? The export button is drawn with no conditions really😅

**Comment by espressodru** [comment]
![WX20241119-223243@2x](https://github.com/user-attachments/assets/f82c3678-2170-4ecf-bb0e-03a0066032de)
Hi, above is the picture
