### ISSUE TITLE
Stop condition

### ISSUE THREAD

**Issue by AsherJingkongChen** [ArthurBrussee/brush#59]
I found the previous version does not stop at the iteration 30000.

1. How do I stop at the specific iteration and run evaluation?
2. How do I export rendered images for further comparison?

**Comment by ArthurBrussee** [comment]
The answer to both kinda sorta is rerun

1. Evaluation gets run every N steps and logged to rerun, so you can always check what PSNR was at 30.000
2. You could save the images logged to rerun. It's definitely a hassle though....

This very much should be improved! Some options to write out images, and a max iteration where to actually stop, should make longer runs easier. See also https://github.com/ArthurBrussee/brush/issues/29

Help always much appreciated :)

**Comment by AsherJingkongChen** [comment]
Thanks, I will try it through Rerun.io
