### ISSUE TITLE
Longer training time than the previous version

### ISSUE THREAD

**Issue by AsherJingkongChen** [ArthurBrussee/brush#64]
Around the middle of November, I have trained splats by 30k iterations on T&T's train. It took 2 hours (exactly) on my Apple M2 Pro (Metal 3).

Recently (1e27349d2a0c88b863a2b901aff1634606bd7582), I have tried again with the same number of iterations. It took 4 hours, which is much slower than previous version. However, the number of splats are much more than the previous one.

I would like to ensure which version is fair for performance comparison against other softwares with the maintainers. Though I have access to an NVIDIA card, I have not tested Brush training yet.

This is the screen shot at 9.5k iterations, I think it is not likely to finish in the rest 1 hours:

<img width="770" alt="image" src="https://github.com/user-attachments/assets/a5a0d0a7-ac3d-4e23-85bf-6c8593201255">

**Comment by ArthurBrussee** [comment]
Hiya! Guess you're getting closer to release, congrats :D Excited to see how it compares.

Brush indeed has recently gotten way slower. I didn't quite realise how bad it was! After some profiling I saw it was mainly just the housekeeping of screenspace gradients... Annoying. I've written a custom cube kernel now: https://github.com/ArthurBrussee/brush/commit/edb01fb68c4ff37f9d4777b280d1c393c2786e38 that seems to resolve this.

If you could redo your evaluations at head that would be much appreciated! Sorry for the hassle.

**Comment by AsherJingkongChen** [comment]
Thanks
