### ISSUE TITLE
Feature: Automatic export every X training steps

### ISSUE THREAD

**Issue by jdiaz97** [ArthurBrussee/brush#67]
My laptop isn't great, so it's likely the app will crash, and I won't have the chance to export the model.
I’d like a feature that allows me to set automatic exports every X training steps, ideally overriding the previous export so I don’t end up with too many files.

**Comment by fasteinke** [comment]
I second that ...

**Comment by ArthurBrussee** [comment]
This was done as part of https://github.com/ArthurBrussee/brush/pull/69! 

It's an option in the CLI as well as in the UI. There's some more ideas for what could be done if we want to make this a proper checkpointing mechanism in https://github.com/ArthurBrussee/brush/issues/29, but, at least "export every so many steps" is in
