### ISSUE TITLE
Use hardware atomic floats when available

### ISSUE THREAD

**Issue by Am0g-us** [ArthurBrussee/brush#8]
***
cargo run --release
    Finished `release` profile [optimized] target(s) in 0.79s
     Running `target/release/brush_bin`
"sparse/0/cameras.bin" "sparse/0/images.bin"
[2024-10-26T16:15:28Z ERROR wgpu_core::device::global] Device::create_shader_module error: 
    Shader validation error: 
    
    
[2024-10-26T16:15:28Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'async-std/runtime' panicked at /home/amongus/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_shader_module
    
Shader validation error: 

      Type [12] '' is invalid
        Capability Capabilities(SHADER_FLT32_ATOMIC) is required

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
"sparse/0/cameras.bin" "sparse/0/images.bin"
[2024-10-26T16:15:52Z ERROR wgpu_core::device::global] Device::create_shader_module error: 
    Shader validation error: 
    
    
[2024-10-26T16:15:52Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'async-std/runtime' panicked at /home/amongus/.cargo/git/checkouts/wgpu-f9afa33caa1e84c9/ffb4852/wgpu/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_shader_module
    
Shader validation error: 

      Type [12] '' is invalid
        Capability Capabilities(SHADER_FLT32_ATOMIC) is required
***
My gpu is amd 6900 xt. Installed latest rocm and mesa drivers.

**Comment by ArthurBrussee** [comment]
Ah yes - I think that's the same as https://github.com/ArthurBrussee/brush/issues/6!

I've disabled hardware atomic floats for now, but should re-enable them soon with proper detection whether they are supported! Will leave this issue open until that's done.

**Comment by AsherJingkongChen** [comment]
I guess that it hardly works on AMD GPUs. 
The Vulkan extension was originally contributed by NVIDIA's developers.

Accessibility issues of float atomic operations can be solved by atomic CAS loop on integer types.

Track gfx-rs/wgpu#6234

**Comment by ArthurBrussee** [comment]
I'm now checking properly whether this feature is supported and use it if so. Let's see if mroe issues pop up.
