### ISSUE TITLE
(Feature request) Select GPU

### ISSUE THREAD

**Issue by Astatin3** [ArthurBrussee/brush#9]
With this project, is it possible to choose which gpu the training will take place on? It seems to default to the 0th gpu on the computer, which is not always the most performant one.

**Comment by ArthurBrussee** [comment]
Ok! I think that's technically more a bug with wgpu (or windows?), as the logic should already be to pick the dedicated GPU, but either way good to have an override! egui PR just landed so now just the Burn one. Burn is having some issues at head but hope to have those resolved soon

**Comment by ArthurBrussee** [comment]
Ok I resolved the last few issues in the Burn update, and landed the selection! After this PR https://github.com/ArthurBrussee/brush/commit/820deb5afe30df65718d0fec461bbbff8d9845cd

You can set the CUBECL_WGPU_DEFAULT_DEVICE env variable to pick between GPUs like this:

```
CUBECL_WGPU_DEFAULT_DEVICE=DiscreteGpu(1)  // Use discrete GPU index 0
CUBECL_WGPU_DEFAULT_DEVICE=IntegratedGpu(0) // Use integrated GPU index 0
```

Again I suspect there's a bug in wgpu so they might both be reported as dedicated / integrated, not sure.

I've added a display of what GPU is being used: https://github.com/ArthurBrussee/brush/commit/809c1d8055327c5927510924d834b76d82f53ea6

Lmk if that works!

**Comment by Astatin3** [comment]
Thank you! It appears to select the correct device now. But it has another error unfortunately, It fails with: `There was no valid format for the surface at all.`
```
(base) astatin3@acer:~/Documents/GitHub/brush$ CUBECL_WGPU_DEFAULT_DEVICE="DiscreteGpu(0)" RUST_BACKTRACE=1 cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/brush_bin`
[2024-11-01T17:21:08Z ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_support: Initialization of an object has failed
[2024-11-01T17:21:08Z ERROR eframe::native::run] Exiting because of error: WGPU error: There was no valid format for the surface at all.
thread 'main' panicked at crates/brush-desktop/src/main.rs:33:10:
called `Result::unwrap()` on an `Err` value: Wgpu(NoSurfaceFormatsAvailable)
stack backtrace:

   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1677:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1102:23
   4: brush_bin::main
             at ./crates/brush-desktop/src/main.rs:28:9
   5: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ArthurBrussee** [comment]
Hmmm well that would also explain why it wasn't picked before - it seems wgpu doesn't believe it can support rendering the surface / window. Do you have other graphical applications that do run on this GPU? I'm not sure how integrated + dedicate GPU stuff works on Linux.

**Comment by Astatin3** [comment]
Sorry for the late response,
This should be the only program that is running on that GPU.

I believe this is solved, I have run into Linux support problems.
